FROM openjdk:11-jdk-slim
VOLUME /tmp
ARG JAR_FILE=backend/target/claims-platform.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
EXPOSE 8080
